### ISSUE TITLE
Digit “3” is not displayed correctly in Libertinus Serif SemiBold

### ISSUE THREAD

**Issue by Ransom77** [alerque/libertinus#524] opened 2022-12-19 16:14 UTC
Hello,

the digit “3” is not displayed correctly in Libertinus Serif SemiBold:
![Libertinus Serif SemiBold](https://user-images.githubusercontent.com/66835201/208469681-ad5e48d2-883a-49bc-96b1-ffcdc6e8c768.png)
However, this phenomenon occurs in the [“Unofficial version of Libertinus Serif” (7.052)](https://github.com/StefanPeev/libertinus/releases), not in the [official version (7.040)](https://github.com/alerque/libertinus/releases).

I like version 7.052 (much) better, because it does not list two extra fonts for the semibold variant in the font menu of a word processor, but only one (“SemiBold”) and the italic variant can be set by clicking the Italic button.

Regards
Ransom

**Comment by hvoss49** [comment] 2022-12-19 20:08
> Am 19.12.2022 um 17:14 schrieb Ransom77 ***@***.***>:
> 
> the digit “3” is not displayed correctly in Libertinus Serif SemiBold:


I cannot see it with lualatex:





By the way: the font names looks wrong to me:


bash-3.2$ otfinfo -i LibertinusSerif-SemBdIta.otf 
Family:              Libertinus Serif SemiBold
Subfamily:           Italic
Full name:           Libertinus Serif SemBd Ita
PostScript name:     LibertinusSerif-SemBdIta

Should be 
Libertinus Serif SemiBold Italic
LibertinusSerif-SemiboldItalic


Then any font manager like font spec for xe/lualatex
Can find the fonts by its family name.

Herbert

**Comment by Ransom77** [comment] 2022-12-19 21:18
@Herbert

This is what the “3” looks like in LibreOffice Writer [v.7.3.7.2 (x64)].

You are absolutely right about the wrong font name. I have corrected it using FontForge in all layers (“PS Name”, “OS/2”, “TTF Names”) and attached the “correct” font [here](https://www.swisstransfer.com/d/87f80a86-801a-41a3-943f-80b1243a7a8a).

Greetings,
Ransom

**Comment by cionx** [comment] 2023-02-03 04:56
This seem to be a problem with @StefanPeev’s development branch, so this problem should probably be reported in his pull request (https://github.com/alerque/libertinus/pull/520).

**Comment by StefanPeev** [comment] 2023-02-03 09:43
@cionx @Ransom77 @hvoss49 I closed pull request #520 and I'll close also all updates on Libertinus Serif. The reason is that I started a project [Common Serif](https://github.com/StefanPeev/Common-Serif) which is further development of Libertinus Serif but with a lot of changes. The aim of the project is to create masters (Regular and Bold, Italic and Bold Italic), which to be compatible and by which we to have a chance to generate instances like this (Regular, Medium, SemiBold, Bold; Italic, Medium Italic, SemiBold Italic, Bold Italic). All this means a serious changes in the project, it is why I think we need a new start. If you like the idea, please, give your notices on [Common Serif](https://github.com/StefanPeev/Common-Serif) repo.

**Comment by StefanPeev** [comment] 2023-02-03 12:36
@cionx @Ransom77 @hvoss49 The problem is solved in v.1.001 of [Common Serif](https://github.com/StefanPeev/Common-Serif/tree/main/sources).

**Comment by waldyrious** [comment] 2023-02-04 00:45
Closing this since it is (was) not an issue in this repository's sources, but rather in (what is now) Common Serif; and in any case it's been fixed there. Thanks all for the updates!

**Closed by waldyrious** 2023-02-04 00:45 UTC
