### ISSUE TITLE
Small Caps Not Working (in v6.12 – v7.031)

### ISSUE THREAD

**Issue by Darkwing371** [alerque/libertinus#434] opened 2021-01-20 14:43 UTC
Could it be that there's an error in the OpenType Feature for **small caps?**

Just downloaded the latest version (7.031) of the Libertinus pack and tested in InDesign: Serif and Sans do not produce the small caps, Display and some others do.

It only seems so work with the "i". This letter accurately is substituted with the small cap glyph.

I consider this bug critical and it should be checked and a new version rolled out asap.

**Thanks and thanks for your work!**

**Comment by alerque** [comment] 2021-01-21 04:26
This would be a serious regression, but I am unable to confirm it is an issue. I just tested both Serif and Sans faces as well as bold and italic styles in English and Turkish (which has dotted and undotted i's and hence a problematic one for small caps if everything isn't working right). Everything checks out in 7.031.

![2021-01-21_07-24](https://user-images.githubusercontent.com/173595/105280046-f5738c80-5bb9-11eb-826a-7a9003ced0d4.png)

<details>
<summary>SILE Code</summary>
```sile
\begin{document}
\neverindent
\begin{raggedright}
\font[size=30pt]
\font[family=Libertinus Serif]
Caleb \em{is} a \strong{hedgehog}. \font[language=tr]{Iı İi}\break
\font[features=+smcp]{Caleb \em{is} a \strong{hedgehog}. \font[language=tr]{Iı İi}}

\font[family=Libertinus Sans]
Caleb \em{is} a \strong{hedgehog}. \font[language=tr]{Iı İi}\break
\font[features=+smcp]{Caleb \em{is} a \strong{hedgehog}. \font[language=tr]{Iı İi}}
\end{raggedright}
\end{document}
```
</details>

**Comment by Darkwing371** [comment] 2021-01-21 15:07
Ok, thanks for checking! Then I'll need to investigate further why this behavior occures.

![libertinus-scaps-bug](https://user-images.githubusercontent.com/3890213/105369054-78203a00-5c02-11eb-86dd-6cc2da25cbb5.jpg)

With the „old“ Linux Libertine and all other fonts I use, there was never such a problem. I'll try some older releases af Libertinus and see if that behavior starts maybe with a specific release version.

**Comment by Darkwing371** [comment] 2021-01-21 16:48
Alright, I tested through the different versions now. Last know working version is 6.11. **Since version 6.12 upwards** this “error” occurs.

It is obvious that the filesize of the fonts in general nearly halfed since v6.12. So this means, there must a some kind of different “internal compression” going on, or the way the font files are build is completly different somehow. This may include the way OpenType Feature Tables are stored – and could cause some weird compatiblity problems in some softwares. I read the changelogs and they said, that since v6.12 you abandoned FontForge as a tool in favour of a different one – I suppose Fontship, that is mentioned in v7.000. 

I hope I was able to convice you so far, that the new workflow you use since v6.12 causes this problem and needs further investigation and tweaking. I hope you can  experiment with some exporting or compression options of Fontship, or anything else to fix this unfortunate behavior.

Should you be unable to test different font files with different settings – since you are unable to reproduce the behavior in the first place – I will help you and test the files for you. Just reply here accordingly and I get in touch with you via email, so we can try to figure out what's the best solution to writing compatible files.

I fear that this weird behavior I ran into could be just a shadow hurrying ahead of a much bigger problem that could occur in the future of the font. You definately should try to figure out why this happens.


So long and thanks for your work on the font!

**Comment by alerque** [comment] 2021-01-21 17:54
All of the 6.x series were released by Khaled. He did phase out using the Python bindings to FontForge as a way to manipulate the font during the build process. For the 7.x series I did switch the build system to Fontship, but under the hood that is using very generic and well known tools such as `fontmake` to actually build the fonts, it just wraps the tooling in an easier workflow.

Since the trouble started in 6.12 Fontship isn't the issue. I am still using some of the same custom Python functions developed for 6.12 (Fontship just handles calling them), so we'll look into that. Your probably right in that something got optimized away or mistakenly not included.

**However**, I still can't replicate this. As I said and showed the SmallCaps feature is working just fine in the released 7.031 font files. I suspect this might be a language related issue. Calculating which glyphs to substitute with is dependent on the shaper knowing what language the text is in. I see you are writing "Test of Libertinus" as if your content was in English, but your UI is in another language. That makes me suspect that your content is also tagged as some other language (is that Dutch? German?). Can you do a test with the content specifically tagged as English? And also let me know what language you are having trouble with so I can check the language tagging in the font features.

**Comment by ivo-s** [comment] 2021-01-21 23:17
I tested the newest release in LibreOffice and the features, including small caps, also work fine. How about other OTF features?

**Comment by Bolpat** [comment] 2021-01-21 23:51
I just tested v7.31 in XeLaTex in various languages, German (@Darkwing371 has a German interface for sure, I'm German), English, Turkish and Romanian. Everything seems fine. All in all, it seems like this is a bug in InDesign and not the font.

**Comment by alerque** [comment] 2021-01-22 07:53
Thanks for the extra testing @ivo-s and @Bolpat, that's helpful.

I suspected an InDesign bug right away (and still do). Adobe's shaping systems are notoriously *bad*. I'm also not particularly motivated to invest a bunch of my volunteer time trying to work around bugs in software written by a multi-hundred billion dollar company that is known for terribly buggy implementations of text shaping.

That being said I am curious to understand why v6.11 works and all later versions do not. The size decrease noted by @Darkwing371 bisects to 61f0348. The mechanics of *how* the subr is implemented has changed completely since then but it's still happening. I suspect Adobe's bug might be in this area, although Adobe's own type blog mentions using [the exact tooling we're using](https://blogs.adobe.com/CCJKType/?p=917) for this, so it probably isn't a matter of support vs. no support but of buggy support.

Fontship does not have a configuration flag to turn *off* cffsubr (it's quite an industry standard at this point), but I modified the build rules to skip it. @Darkwing371 can you try this font file: 
[no-subr.zip](https://github.com/alerque/libertinus/files/5854295/no-subr.zip).

**Comment by Darkwing371** [comment] 2021-01-22 09:21
Thanks @ all for taking care!

I also tested different things with the latest font release. I tried the OTF in the browser by using the small caps property in CSS and I tried the latest version of LibreOffice using the small caps: yes, I can confirm, it works as expected and real OpenType small caps are shown.

Nevertheless the "InDesign bug" must be triggered by something inside of the font – because it is the only font (I emphasize: **only** font) where this wierd behavior occurs. I also tested the "no-subr font", 7.031 [3d1db57]-dev. This is the result: no difference, wierd behavior still there:

![versionsvergleich-2](https://user-images.githubusercontent.com/3890213/105469969-44dcba00-5c99-11eb-8e37-8a26c4cb6af2.jpg)

Still it's just the "i" that is substituted with its small cap version. Why the "i"? I also tried marking the text as English language, but it made no difference.

I read that there seem to be two different "flavours" of builing such kind of OpenType features into a font: either via some kind of "substitution table" or being directly "encoded" into the font. I don't know if that makes any sense and could be a hint … I admit that at this level of technical depths I have no further knowledge (yet).

I just know: Libertinus worked perfeclty in version 6.11, but later became quirky.

@alerque Can you elaborate on the _"mechanics of how the subr is implemented has changed completely"?_ Can you post a link to an article of what this could mean?

**Comment by alerque** [comment] 2021-01-22 09:37
> I also tested different things with the latest font release. I tried the OTF in the browser by using the small caps property in CSS and I tried the latest version of LibreOffice using the small caps: yes, I can confirm, it works as expected and real OpenType small caps are shown.

Yes, I'm pretty confident at this point that the OpenType font itself is valid and correct and that InDesign's handling is wrong.

By the way I haven't seen from you what language your content is tagged in in InDesign. Did you try it with the content tagged as English? Can you please try the string `İiIı` with the content language tagged as Turkish just to prove that the language tagging is working correctly. Use another font if you need to to confirm the case changes are happening properly in Turkish and *not* if the language is set to English. That way we can rule out this being a content language issue.

> Nevertheless the "InDesign bug" must be triggered by something inside of the font – because it is the only font (I emphasize: **only** font) where this wierd behavior occurs. I also tested the "no-subr font", 7.031 [[3d1db57](https://github.com/alerque/libertinus/commit/3d1db5777d4a071f643f254d31ab1666df52c1f4)]-dev. This is the result: no difference, wierd behavior still there:

Yes, I agree there must me something specific that is tripping up InDesign or at least some way it would be worked around that we're not doing any more. We'll keep looking for what that is.

I'm actually not convinced my test font build actually didn't have cffsubr run on it, the file size should have been larger...

> Still it's just the "i" that is substituted with its small cap version. Why the "i"? I also tried marking the text as English language, but it made no difference.

Why the I? Probably because InDesign is not passing the correct script/language settings to the shaper. Hence why I want you to test the string above in English and Turkish.

> @alerque Can you elaborate on the _"mechanics of how the subr is implemented has changed completely"?_ Can you post a link to an article of what this could mean?

Initially in v6.12 we were using `tx` and manually extracting, munging, and re-inserting data. Now we directly use Adobe's own Python based [`cffsubr`](https://pypi.org/project/cffsubr/) library.

**Comment by alerque** [comment] 2021-01-22 09:40
My last zip file had the wrong test font file in it! Try this one instead: [no-subr-2.zip](https://github.com/alerque/libertinus/files/5854896/no-subr-2.zip)

**Comment by alerque** [comment] 2021-01-22 09:48
> ![versionsvergleich-2](https://user-images.githubusercontent.com/3890213/105469969-44dcba00-5c99-11eb-8e37-8a26c4cb6af2.jpg)

Also color me a little bit skeptical of your tests here. What you claim in this test is `Libertinus Serif Semibold 6.11` is not the semibold weight and it is the italic style.

How sure are you that you don't have multiple copies of font files installed somewhere the system is picking up on them? Is there any debug information in InDesign that shows exactly what font file and features were used to render a given text (something like the inspector available in most browsers)?

**Comment by Darkwing371** [comment] 2021-01-22 10:42
Oops, sorry for making you confused, but it was just me not changing the written text to the actual font style I used. All the tests and font file swapping I do with the Serif Regular; of it I installed the 7.031-dev version – all other variants on my system are version 6.11 at the moment. At first I wanted to use the semibold to show version 6.11, but later I decided for italic – but overlooked to change the text accordingly. So no problem here, just a mistake.

But since I found it easily I can even provide proof of the used files:


![proofofversion7](https://user-images.githubusercontent.com/3890213/105480004-7bb8cd00-5ca5-11eb-90b5-2c3a374f2ce8.jpg)

![proofofversion6](https://user-images.githubusercontent.com/3890213/105480136-a73bb780-5ca5-11eb-825e-ca3202b98af9.jpg)

![proofofversionused](https://user-images.githubusercontent.com/3890213/105480024-82dfdb00-5ca5-11eb-862a-44677f289560.jpg)

I installed now version 7.031;[3d1db57]-dev from the **second archive** you provided (the bigger file) and it is also really installed:

![proofofversionarchive2](https://user-images.githubusercontent.com/3890213/105480878-9b9cc080-5ca6-11eb-865c-4d5ee78cfbe9.jpg)

But for more clarity maybe you should give future dev releases a different build number or dev number.


So far about the used font files.

**Comment by Darkwing371** [comment] 2021-01-22 11:01
Now about the test string you suggested – here it is:

![versionsvergleich-2b](https://user-images.githubusercontent.com/3890213/105481843-e2d78100-5ca7-11eb-846e-ded976c910c7.jpg)

I made sure to tag the text frames with the specific content language. You see, that Turkish does something different. But you also see, that the types of ligatures don't become replaced by the corresponding small cap versions. Bummer!

Sidenote:
And you can also see that almost no font has a small cap version of the Capital Sharp S. Challange: Be the first one on earth who has built it in his font. =D I mean ... it's logical, isn't it? ;)

So far I hope my test results can give you a hint where there lies the hare in the pepper.

**Comment by alerque** [comment] 2021-01-22 11:22
> Now about the test string you suggested – here it is:

Ore those strings all marked as smallcaps? Did you try them in other fonts too?

> I made sure to tag the text frames with the specific content language. You see, that Turkish does something different. But you also see, that the types of ligatures don't become replaced by the corresponding small cap versions. Bummer!

The small cap feature does work with ligatures:

![image](https://user-images.githubusercontent.com/173595/105484546-8df23580-5cbc-11eb-99f9-e4cff2d2c9a0.png)

But that brings up the interesting point that you have **other** open type features turned on such as stylistic alternates. The `Th` and `st` ligatures are not on by default. Try turning those off and see if your small caps start working.

> Sidenote:
> And you can also see that almost no font has a small cap version of the Capital Sharp S. Challange: Be the first one on earth who has built it in his font. =D I mean ... it's logical, isn't it? ;)

No it isn't logical, your expectations here are off. You can't have "small caps" versions of capital letters because by definition the [OpenType spec](https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#tag-smcp) for the `+smcp` feature is to convert lower case letters to small versions of upper case forms:

> This feature turns glyphs for lowercase characters into small capitals.

Hence why no other fonts do this. If you want that you need to convert to lower case first. You can do with with OpenType using the [`+c2sc` feature](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#c2sc).

And yes combining `+smcp,+c2sc` works in Libertinus Serif:

![image](https://user-images.githubusercontent.com/173595/105484963-3bfddf80-5cbd-11eb-9189-7f7724fffceb.png)

**Comment by Darkwing371** [comment] 2021-01-22 11:54
Ok, during my tests I deliberately turned on some other OpenType features just to show that they are working correctly. This can not be the source of the quirk, because I had them disabled at the begining, turned them on in later tests and now have them turned off again completely – except for the small caps. And yes, all the strings are marked to become small capsy.

![versionsvergleich-2c-allfeaturesturnedoff-justcaps](https://user-images.githubusercontent.com/3890213/105487169-f555b880-5caf-11eb-9865-5d60ce27dda8.jpg)

For the sake of clear view I'll soon alter my test document I post screenshots here of. I think its better to use an alphabete.

(And about the Capital Sharp S I'll convice you in a different thread. ;) Let's not mix topics here.)

**Comment by khaledhosny** [comment] 2021-01-22 14:06
I’m almost certain the fix for https://github.com/alerque/libertinus/issues/303 is what trips InDesign. Before this fix smalllcaps lookups were single substitution lookups like most fonts, after that they became multiple substitution lookups. Adobe’s OpenType implementations are known for all sorts of misguided assumptions, and that snap feature always uses single substitution lookups might be one of them.

You might get better luck using World Ready Composer, or HarfBuzz (both should be supported by latest InDesign and you can look up how to use them).

**Comment by khaledhosny** [comment] 2021-01-22 14:17
(It would have been hilarious is using Adove’s subroutininzer, cffsubr, would cause such an issue).

**Comment by Darkwing371** [comment] 2021-01-22 16:12
Well, at first I thought dealing with the Capital Sharp S would be off topic, but now that I researched this more: maybe this gives us a better understanding of what is going on.

I tested this in InDesign and the result is:
![versionsvergleich-3-versaleszett](https://user-images.githubusercontent.com/3890213/105512218-1f6ba280-5cd1-11eb-9e59-f5cbd763b141.jpg)

Not only the small caps aren't working correctly, but also the substitution of the all caps feature isn't working correctly. It does substitue ß → SS instead of ß → ẞ. What a bummer!

This whole behavior seems to be consistent througout Adobe Creative Suite 5 – I tested in Photoshop CS5 and InDesign CS5. Thou professional, since it is a fairly old software (2010) I'm at the verge of starting to believe that it is the inner workings of the typesetting software that produces this behavior, because "it doesn't know better". (But maybe it's still two separate problems, who knows.)

I'm beginning to believe, that the font format standards changed over time so dramatically, that older software, that's nevertheless fully capable of OpenType features, don't understand the new formats and "spots for saving things" the fonts have inside nowadays.

I tested it again in the browser with CSS properties, et voilá: it works and is all there.

![versionsvergleich-6-7-browsercss](https://user-images.githubusercontent.com/3890213/105514350-acaff680-5cd3-11eb-9871-01e224d613a2.jpg)


Oh boy ... do I really need an Adobe Creative Cloud Abo because fonts grow more and more into "incompatiblity"?  =o  Nasty move, big tech ...


**Philosophical question:** Should fonts be as compatible as possible, or should they always embrace the latest technology and don't be backwards compatible, so that only the spearhead elitists can fully use them?

**Comment by Darkwing371** [comment] 2021-01-22 16:28
Back to the small caps an the "i": I made a more clear test document now. Here you can have a better overview of what is substituted and what not.

![versionsvergleich-3](https://user-images.githubusercontent.com/3890213/105516431-2943d480-5cd6-11eb-91d8-aa22fd742735.jpg)

If we leave out the Sharp S for now, can we solve the puzzle with the "i"? It seams to be substituted partially correct with the Turkish letters, right? So does it have to do something with language zones or the like?

Also could you please check whether the size of the subroutines that are encoded, exceed a certain limit as described in your [linked article](https://blogs.adobe.com/CCJKType/2012/02/subroutinization.html)? This could be interesting!

**Comment by ivo-s** [comment] 2021-01-22 18:40
I am getting a bit lost. The puzzle with the "i" has been answered by Khaled. There are 3 `smcp` lookup tables. Two contain just the "i" for purposes of including the dot in certain languages. One contains all the other letters. In terms of sequence, as displayed by FontForge, the table with the dotless "i" comes first, which strongly suggests that the software stops at the first lookup table, where there is only one entry, and therefore substitutes only "i". As to *why*, we do not know, but since you are using the discontinued Adobe CS5, the fonts work all right in other software, there are no objective bugs in the fonts that can be identified, I think there is nothing to look for. If the fonts compiled without subroutines didn't help, then the thing that triggers the CS5 bug can be anything, and quite likely cannot be turned off or fixed.

I also noticed that you are confusing small-cap substitution of the sharp s with an alternate stylistic set 3. The `ss03` feature replaces the sharp s symbol with "ss" in all variants - lowercase, capital, and small caps. You obviously have that turned on. Without it, both capital and lowercase eszett work correctly, and properly convert into small-caps, as I showed in the image above. And there is no "all-caps substitution feature" in the OTF format that I know of. If you have something like that available, it is purely InDesign functionality.

It is bad that CS5 cannot handle some new fonts, but you generally cannot expect any software to be compatible into the future. I know from experience that the stuff I created in Adobe Flash CS5 in 2010 did not function properly in Adobe's own Flash Player some years later.

**Comment by Darkwing371** [comment] 2021-01-22 19:11
... oh right, I forgot to mention in my lengthy post: I do **not** have Stylisitc Set 3 turned on. The SS-Substitution happens on its own.

![versionsvergleich-3-ss3](https://user-images.githubusercontent.com/3890213/105533456-7632a580-5cec-11eb-9421-70e028455c0c.jpg)

And yes, maybe it's an InDesign option, but it uses the OpenType features or a combination thereof, like demonstrated in our thread above:

![versionsvergleich-3-choices-2](https://user-images.githubusercontent.com/3890213/105534187-68c9eb00-5ced-11eb-9385-a4fd22398228.jpg)

Anyway, I also believe this doesn't matter and leads the thread astray.

What I will do in the following days, is to download the test version of the latest InDesign CC and see what the behavior is there.

**Comment by alerque** [comment] 2021-01-23 16:33
> I'm beginning to believe, that the font format standards changed over time so dramatically, that older software, that's nevertheless fully capable of OpenType features, don't understand the new formats and "spots for saving things" the fonts have inside nowadays.

No, the OpenType spec has not changed in this regard.

> I tested it again in the browser with CSS properties, et voilá: it works and is all there.

Yes, because the font is fine.

> Oh boy ... do I really need an Adobe Creative Cloud Abo because fonts grow more and more into "incompatiblity"? =o Nasty move, big tech ...

The version you are using was broken when you bought it and Adobe wants you to fork over more money for a version that is slightly less broken (but still known to be broken in many ways). Not my problem. The font (provided free of charge) correctly adheres to the decades old font format standard and many free software packages exists that can correctly shape it. Browsers, word processors, specialty print layout engines etc.

It's really not my problem Adobe is ripping you off.

> **Philosophical question:** Should fonts be as compatible as possible, or should they always embrace the latest technology and don't be backwards compatible, so that only the spearhead elitists can fully use them?

Fonts should be compatible with the spec. The spec already dictates many steps just for backwards compatibility, and spec compliant fonts work with spec compliant software from decades ago. Fonts should not be expected to make up for buggy shapers that don't actually follow specs. And the more so when the font project developers are donating their time and the buggy software shaper is from a $240 billion dollar company.

**Closed by alerque** 2021-01-23 16:33 UTC
Labels: bug, needs info, script latin

**Comment by alerque** [comment] 2021-01-23 16:50
By the way you are welcome to try building yourself a version without the macron fix.

```console
$ git revert f915575
$ fontship make -- otfs
```

The result may work for your purposes, but since it would be a regression on other issues I won't be considering that for mainline inclusion. If there is anything than needs to be done to have a valid working OpenType font that conforms to the spec then of course I would consider that, but that does not seem to be the case here. Literally **all** of the issues you've brought up work fine in the font using normal OpenType mechanisms, the issue is your not using an open-type compatible piece of software (however much their marketing might have led you to believe the contrary).
